robots:
    jackal:
        name: "jackal"
        isaac_asset_path: "/root/giacomo_ws/src/jackal/jackal_simulator/jackal_isaac/description/jackal_isaac.usd"
        wheel_joint_names: ["front_left_wheel_joint", "front_right_wheel_joint", "rear_left_wheel_joint", "rear_right_wheel_joint"]
        position: [0.0, 0.0, 0.5]
        orientation: [0.0, 0.0, 0.0, -1.0]
        cameras:
            camera_color:
                frame_id: "camera_color_optical_frame"
                prim_path: "/camera_color_optical_frame/camera_color"
                enable_rgb: True
                enable_depth: True
            camera_left:
                frame_id: "camera_infra1_optical_frame"
                prim_path: "/camera_infra1_optical_frame/camera_left"
                enable_rgb: True
                enable_depth: False
            camera_right:
                frame_id: "camera_infra2_optical_frame"
                prim_path: "/camera_infra2_optical_frame/camera_right"
                enable_rgb: True
                enable_depth: False
        lidar:
            prim_path: "/front_laser/lidar"
            enable_scan: True
            enable_pcl: True
        imu:
            prim_path: "/imu_link/imu"

stage:
    usd_path: "/root/giacomo_ws/pergola/vigna_a_pergola_default.usd"
    root_prim_path: "/Empty"
    physics_update_rate: 400.0 # as set in examples - rendering is 8 times slower